/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectLink = IDL.Record({
  'url' : IDL.Text,
  'labelText' : IDL.Text,
});
export const ProjectInput = IDL.Record({
  'techTags' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'links' : IDL.Vec(ProjectLink),
  'summary' : IDL.Text,
  'imageRef' : IDL.Opt(IDL.Text),
});
export const Id = IDL.Nat;
export const WriteError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : Id,
});
export const Skill = IDL.Record({
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'proficiency' : IDL.Nat,
});
export const SkillGroupInput = IDL.Record({
  'order' : IDL.Nat,
  'category' : IDL.Text,
  'skills' : IDL.Vec(Skill),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Project = IDL.Record({
  'id' : Id,
  'techTags' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'links' : IDL.Vec(ProjectLink),
  'summary' : IDL.Text,
  'imageRef' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'read' : IDL.Bool,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SkillGroup = IDL.Record({
  'id' : Id,
  'order' : IDL.Nat,
  'category' : IDL.Text,
  'skills' : IDL.Vec(Skill),
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [ProjectInput],
      [IDL.Variant({ 'ok' : Id, 'err' : WriteError })],
      [],
    ),
  'createSkillGroup' : IDL.Func(
      [SkillGroupInput],
      [IDL.Variant({ 'ok' : Id, 'err' : WriteError })],
      [],
    ),
  'deleteProject' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
      [],
    ),
  'deleteSkillGroup' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([Id], [IDL.Opt(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listSkillGroups' : IDL.Func([], [IDL.Vec(SkillGroup)], ['query']),
  'markMessageRead' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitContactMessage' : IDL.Func(
      [ContactInput],
      [IDL.Variant({ 'ok' : Id, 'err' : WriteError })],
      [],
    ),
  'updateProject' : IDL.Func(
      [Id, ProjectInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
      [],
    ),
  'updateSkillGroup' : IDL.Func(
      [Id, SkillGroupInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectLink = IDL.Record({ 'url' : IDL.Text, 'labelText' : IDL.Text });
  const ProjectInput = IDL.Record({
    'techTags' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'links' : IDL.Vec(ProjectLink),
    'summary' : IDL.Text,
    'imageRef' : IDL.Opt(IDL.Text),
  });
  const Id = IDL.Nat;
  const WriteError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : Id,
  });
  const Skill = IDL.Record({
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'proficiency' : IDL.Nat,
  });
  const SkillGroupInput = IDL.Record({
    'order' : IDL.Nat,
    'category' : IDL.Text,
    'skills' : IDL.Vec(Skill),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Project = IDL.Record({
    'id' : Id,
    'techTags' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'links' : IDL.Vec(ProjectLink),
    'summary' : IDL.Text,
    'imageRef' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'read' : IDL.Bool,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SkillGroup = IDL.Record({
    'id' : Id,
    'order' : IDL.Nat,
    'category' : IDL.Text,
    'skills' : IDL.Vec(Skill),
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [ProjectInput],
        [IDL.Variant({ 'ok' : Id, 'err' : WriteError })],
        [],
      ),
    'createSkillGroup' : IDL.Func(
        [SkillGroupInput],
        [IDL.Variant({ 'ok' : Id, 'err' : WriteError })],
        [],
      ),
    'deleteProject' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
        [],
      ),
    'deleteSkillGroup' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([Id], [IDL.Opt(Project)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listSkillGroups' : IDL.Func([], [IDL.Vec(SkillGroup)], ['query']),
    'markMessageRead' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitContactMessage' : IDL.Func(
        [ContactInput],
        [IDL.Variant({ 'ok' : Id, 'err' : WriteError })],
        [],
      ),
    'updateProject' : IDL.Func(
        [Id, ProjectInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
        [],
      ),
    'updateSkillGroup' : IDL.Func(
        [Id, SkillGroupInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : WriteError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };