/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactMessage {
  'id' : Id,
  'name' : string,
  'read' : boolean,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Id = bigint;
export interface Project {
  'id' : Id,
  'techTags' : Array<string>,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'links' : Array<ProjectLink>,
  'summary' : string,
  'imageRef' : [] | [string],
}
export interface ProjectInput {
  'techTags' : Array<string>,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'links' : Array<ProjectLink>,
  'summary' : string,
  'imageRef' : [] | [string],
}
export interface ProjectLink { 'url' : string, 'labelText' : string }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Skill {
  'order' : bigint,
  'name' : string,
  'proficiency' : bigint,
}
export interface SkillGroup {
  'id' : Id,
  'order' : bigint,
  'category' : string,
  'skills' : Array<Skill>,
}
export interface SkillGroupInput {
  'order' : bigint,
  'category' : string,
  'skills' : Array<Skill>,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type WriteError = { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : Id };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Creates a project. Admin only.
   */
  'createProject' : ActorMethod<
    [ProjectInput],
    { 'ok' : Id } |
      { 'err' : WriteError }
  >,
  /**
   * / Creates a skill group. Admin only.
   */
  'createSkillGroup' : ActorMethod<
    [SkillGroupInput],
    { 'ok' : Id } |
      { 'err' : WriteError }
  >,
  /**
   * / Deletes a project. Admin only.
   */
  'deleteProject' : ActorMethod<[Id], { 'ok' : null } | { 'err' : WriteError }>,
  /**
   * / Deletes a skill group. Admin only.
   */
  'deleteSkillGroup' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : WriteError }
  >,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / A single project by id.
   */
  'getProject' : ActorMethod<[Id], [] | [Project]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Lists contact messages, newest first. Admin only.
   */
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  /**
   * / All projects, ordered for display.
   */
  'listProjects' : ActorMethod<[], Array<Project>>,
  /**
   * / All skill groups with their skills, ordered for display.
   */
  'listSkillGroups' : ActorMethod<[], Array<SkillGroup>>,
  /**
   * / Marks a contact message as read. Admin only.
   */
  'markMessageRead' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : WriteError }
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Submits a contact message from the public contact form.
   */
  'submitContactMessage' : ActorMethod<
    [ContactInput],
    { 'ok' : Id } |
      { 'err' : WriteError }
  >,
  /**
   * / Updates a project. Admin only.
   */
  'updateProject' : ActorMethod<
    [Id, ProjectInput],
    { 'ok' : null } |
      { 'err' : WriteError }
  >,
  /**
   * / Updates a skill group. Admin only.
   */
  'updateSkillGroup' : ActorMethod<
    [Id, SkillGroupInput],
    { 'ok' : null } |
      { 'err' : WriteError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];