/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface ContactInput {
    name: string;
    email: string;
    message: string;
}
export interface ContactMessage {
    id: Id;
    name: string;
    read: boolean;
    submittedAt: Timestamp;
    email: string;
    message: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type Id = bigint;
export interface Project {
    id: Id;
    techTags: Array<string>;
    title: string;
    order: bigint;
    description: string;
    links: Array<ProjectLink>;
    summary: string;
    imageRef?: string;
}
export interface ProjectInput {
    techTags: Array<string>;
    title: string;
    order: bigint;
    description: string;
    links: Array<ProjectLink>;
    summary: string;
    imageRef?: string;
}
export interface ProjectLink {
    url: string;
    labelText: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Skill {
    order: bigint;
    name: string;
    proficiency: bigint;
}
export interface SkillGroup {
    id: Id;
    order: bigint;
    category: string;
    skills: Array<Skill>;
}
export interface SkillGroupInput {
    order: bigint;
    category: string;
    skills: Array<Skill>;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type WriteError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: Id;
};
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Creates a project. Admin only.
     */
    createProject(input: ProjectInput): Promise<{
        __kind__: "ok";
        ok: Id;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    /**
     * / Creates a skill group. Admin only.
     */
    createSkillGroup(input: SkillGroupInput): Promise<{
        __kind__: "ok";
        ok: Id;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    /**
     * / Deletes a project. Admin only.
     */
    deleteProject(id: Id): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    /**
     * / Deletes a skill group. Admin only.
     */
    deleteSkillGroup(id: Id): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown documentation of this backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / A single project by id.
     */
    getProject(id: Id): Promise<Project | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Lists contact messages, newest first. Admin only.
     */
    listContactMessages(): Promise<Array<ContactMessage>>;
    /**
     * / All projects, ordered for display.
     */
    listProjects(): Promise<Array<Project>>;
    /**
     * / All skill groups with their skills, ordered for display.
     */
    listSkillGroups(): Promise<Array<SkillGroup>>;
    /**
     * / Marks a contact message as read. Admin only.
     */
    markMessageRead(id: Id): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    schema(): Promise<string>;
    /**
     * / Submits a contact message from the public contact form.
     */
    submitContactMessage(input: ContactInput): Promise<{
        __kind__: "ok";
        ok: Id;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    /**
     * / Updates a project. Admin only.
     */
    updateProject(id: Id, input: ProjectInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
    /**
     * / Updates a skill group. Admin only.
     */
    updateSkillGroup(id: Id, input: SkillGroupInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }>;
}
import type { Cell as _Cell, Error as _Error, Id as _Id, Project as _Project, ProjectInput as _ProjectInput, ProjectLink as _ProjectLink, Result as _Result, Result__1 as _Result__1, UserRole as _UserRole, Value as _Value, WriteError as _WriteError } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: ProjectInput): Promise<{
        __kind__: "ok";
        ok: Id;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_ProjectInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_ProjectInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSkillGroup(arg0: SkillGroupInput): Promise<{
        __kind__: "ok";
        ok: Id;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createSkillGroup(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSkillGroup(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: Id): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSkillGroup(arg0: Id): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSkillGroup(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSkillGroup(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: Id): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactMessages();
            return result;
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSkillGroups(): Promise<Array<SkillGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSkillGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSkillGroups();
            return result;
        }
    }
    async markMessageRead(arg0: Id): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async submitContactMessage(arg0: ContactInput): Promise<{
        __kind__: "ok";
        ok: Id;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: Id, arg1: ProjectInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSkillGroup(arg0: Id, arg1: SkillGroupInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WriteError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkillGroup(arg0, arg1);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkillGroup(arg0, arg1);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WriteError_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WriteError): WriteError {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n14(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n18(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    techTags: Array<string>;
    title: string;
    order: bigint;
    description: string;
    links: Array<_ProjectLink>;
    summary: string;
    imageRef: [] | [string];
}): {
    id: Id;
    techTags: Array<string>;
    title: string;
    order: bigint;
    description: string;
    links: Array<ProjectLink>;
    summary: string;
    imageRef?: string;
} {
    return {
        id: value.id,
        techTags: value.techTags,
        title: value.title,
        order: value.order,
        description: value.description,
        links: value.links,
        summary: value.summary,
        imageRef: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.imageRef))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    invalidInput: string;
} | {
    notFound: _Id;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: Id;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _WriteError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: WriteError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_WriteError_n9(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Id;
} | {
    err: _WriteError;
}): {
    __kind__: "ok";
    ok: Id;
} | {
    __kind__: "err";
    err: WriteError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_WriteError_n9(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n22(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectInput): _ProjectInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    techTags: Array<string>;
    title: string;
    order: bigint;
    description: string;
    links: Array<ProjectLink>;
    summary: string;
    imageRef?: string;
}): {
    techTags: Array<string>;
    title: string;
    order: bigint;
    description: string;
    links: Array<_ProjectLink>;
    summary: string;
    imageRef: [] | [string];
} {
    return {
        techTags: value.techTags,
        title: value.title,
        order: value.order,
        description: value.description,
        links: value.links,
        summary: value.summary,
        imageRef: value.imageRef ? candid_some(value.imageRef) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
